version: "3.8"
services:
  db: 
    image: docker_db
    build: ../data-access
    restart: always
    ports:
       - ${DB_PORT}:5432
    environment:
       - POSTGRES_PASSWORD=${DB_PASSWORD}
       - POSTGRES_USER=${DB_USER}
       - POSTGRES_DB=${DB_DATABASE}
       - CONNECTION_STRING=postgresql://${DB_USER}:${DB_PASSWORD}@docker_db_1:${DB_PORT}/${DB_DATABASE}
  test-db:
      image: docker_db
      build: ../data-access
      restart: always
      ports:
         - 5430:5432
      environment:
         - POSTGRES_PASSWORD=${DB_PASSWORD}
         - POSTGRES_USER=${DB_USER}
         - POSTGRES_DB=${DB_DATABASE}
         - CONNECTION_STRING=postgresql://${DB_USER}:${DB_PASSWORD}@docker_db_1:${DB_PORT}/${DB_DATABASE}
  app:
    build: ..
    restart: always
    ports:
      - ${CLIENT_PORT}:3000
      - ${SERVER_PORT}:8081
    environment: 
      - DB_URI=postgresql://${DB_USER}:${DB_PASSWORD}@docker_db_1:${DB_PORT}/${DB_DATABASE}
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMIN_PORT}:8080
volumes:
  postgres-data:
    driver: local
  