version: "3.8"
services:
  db: 
    image: docker_db
    build: ../database
    restart: always
    ports:
       - ${DB_PORT}:5432
    environment:
       - POSTGRES_PASSWORD=${DB_PASSWORD}
       - POSTGRES_USER=${DB_USER}
       - POSTGRES_DB=${DB_DATABASE}
       - CONNECTION_STRING=postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}
    volumes:
      - ../database/schemas:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMIN_PORT}:8080
  app:
    image: docker_app
    build: ..
    restart: always
    ports:
      - ${CLIENT_PORT}:3000
      - ${SERVER_PORT}:8081
    environment: 
      - DB_URI=postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}
    depends_on: 
      - db
    volumes:
      - ../../docs/ESdoc:/home/app/docs
volumes:
  postgres-data:
    driver: local
  