version: "3.8"
services:
  postgres: 
    image: postgres:13.2
    restart: always
    ports:
       - ${DB_PORT}:${DB_PORT}
    environment:
       - POSTGRES_PASSWORD=${DB_PASSWORD}
       - POSTGRES_USER=${DB_USER}
       - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  skill-finder:
    image: docker.pkg.github.com/m30819-2020/cw-code-t33/skill-finder
    restart: always
    ports:
      - 3000:3000
      - 8081:8081
    environment: 
      - DB_URI=postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}
      depends_on: 
       - postgres
volumes:
  postgres-data:
    driver: local
  