version: "3.8"
services:
  skill-finder:
    image: docker.pkg.github.com/m30819-2020/cw-code-t33/skill-finder
    restart: always
    ports:
      - 3000:3000
      - 8081:8081
  postgres: 
    image: postgres:13.2
    restart: always
    environment:
       - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  postgres-data:
    driver: local
  