version: "3.8"
services:
  db: 
    image: postgres
    restart: always
    ports:
       - 5432:5432
    environment:
       - POSTGRES_PASSWORD=${DB_PASSWORD}
       - POSTGRES_USER=${DB_USER}
       - POSTGRES_DB=${DB_DATABASE}
       - CONNECTION_STRING=postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}
    volumes:
      - ../database/schemas/:/docker-entrypoint-initdb.d/
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  app:
    image: skill-finder
    ports:
      - 3000:3000
      - 8081:8081
    environment: 
      - DB_URI=postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}
    depends_on: 
      - db
volumes:
  postgres-data:
    driver: local
  