version: "3.8"
services:
  db: 
    image: docker.pkg.github.com/m30819-2020/cw-code-t33/skill-finder-db:latest
    restart: always
    ports:
       - ${DB_PORT}:5432
    environment:
       - POSTGRES_PASSWORD=${DB_PASSWORD}
       - POSTGRES_USER=${DB_USER}
       - POSTGRES_DB=${DB_DATABASE}
       - CONNECTION_STRING=postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}
    volumes:
      - ../scripts:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMIN_PORT}:8080
  app:
    image: docker.pkg.github.com/m30819-2020/cw-code-t33/skill-finder:latest
    ports:
      - ${CLIENT_PORT}:3000
      - ${SERVER_PORT}:8081
    environment: 
      - DB_URI=postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}
    depends_on: 
      - db
volumes:
  postgres-data:
    driver: local
  