name: Docker Compose Action Workflow
on: 
  push:
    branches:
      - test-docker
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          DB_USER: ${{github.actor}}
          DB_PASSWORD: password
          DB_DATABASE: skillfinder
      - name: Build Database, and Application Image
        run: docker-compose -f src/docker build
      - name: Tag the Application Image.
        run: docker tag docker_app docker.pkg.github.com/m30819-2020/cw-code-t33/skill-finder:latest
      - name: Tag the Database Image.
        run: docker tag docker_db docker.pkg.github.com/m30819-2020/cw-code-t33/skill-finder-db:latest
      - name: Push the Application Image.
        run: docker.pkg.github.com/m30819-2020/cw-code-t33/skill-finder:latest
      - name: Push the Database Image.
        run: docker.pkg.github.com/m30819-2020/cw-code-t33/skill-finder-db:latest
      - name: Run Application.
        run: docker-compose -f src/docker up -d